name-template: 'v$RESOLVED_VERSION'

tag-template: 'v$RESOLVED_VERSION'

template: |
  # Changelog

  $CHANGES

  See details of [all code changes](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION) since previous release.

categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  default: patch

autolabeler:
  - label: 'fix'
    title:
      - '/^fix[(:]/i'
  - label: 'feature'
    title:
      - '/^feat[(:]/i'
  - label: 'breaking'
    title:
      - '/^.*!: '
    body:
      - '/BREAKING CHANGE/'
