name: "Setup any binary tool"
description: "Cached download of any binary release"
inputs:
  name:
    description: "Name of the tool"
    required: true

  version:
    description: "Version of the tool"
    required: true

  url:
    description: |
      URL to installation archive. This value may contain interpolations for
      name, version, os, arch, and extension.

      `http://example.com/binaries/{name}/{version}.{os}_{arch}.{ext}`

      `{name}` and `{version}` will match the other inputs. `{os}`, `{arch}` and
      `{ext}`, will be inferred, but can be changed by setting additional
      inputs.

  subdir:
    description: |
      Subdirectory within the archive to find the executable(s). Supports the
      same interpolations as `url`.

  os:
    description: "`{os}` to use instead of `process.platform`"

  arch:
    description: "`{arch}` to use instead of `process.arch`"

  ext:
    description: "`{ext}` to use instead of inferring"

  no-extract:
    description: |
      Do not extract the asset as an archive. Rather, expect that it represents
      the (only) binary itself. It will be downloaded, cached, and available on
      `$PATH` as `{name}`.

  url-darwin: { description: "`url` when `platform==darwin`" }
  url-linux: { description: "`url` when `platform==linux`" }
  url-win32: { description: "`url` when `platform==win32`" }
  url-x64: { description: "`url` when `arch==x64`" }
  url-darwin-x64:
    { description: "`url` when `platform==darwin` and `arch==x64`" }
  url-darwin-arm64:
    { description: "`url` when `platform==darwin` and `arch==arm64`" }
  url-linux-x64: { description: "`url` when `platform==linux` and `arch==x64`" }
  url-win32-x64: { description: "`url` when `platform==win33` and `arch==x64`" }
  subdir-darwin: { description: "`subdir` when `platform==darwin`" }
  subdir-linux: { description: "`subdir` when `platform==linux`" }
  subdir-win32: { description: "`subdir` when `platform==win32`" }
  subdir-x64: { description: "`subdir` when `arch==x64`" }
  subdir-arm64: { description: "`subdir` when `arch==arm64`" }
  subdir-darwin-x64:
    { description: "`subdir` when `platform==darwin` and `arch==x64`" }
  subdir-darwin-arm64:
    { description: "`subdir` when `platform==darwin` and `arch==arm64`" }
  subdir-linux-x64:
    { description: "`subdir` when `platform==linux` and `arch==x64`" }
  subdir-win32-x64:
    { description: "`subdir` when `platform==win33` and `arch==x64`" }
  os-darwin: { description: "`{os}` to use when `platform==darwin`" }
  os-linux: { description: "`{os}` to use when `platform==linux`" }
  os-win32: { description: "`{os}` to use when `platform==win32`" }
  os-x64: { description: "`{os}` to use when `arch==x64`" }
  os-arm64: { description: "`{os}` to use when `arch==arm64`" }
  os-darwin-x64:
    { description: "`{os}` to use when `platform==darwin` and `arch==x64`" }
  os-darwin-arm64:
    { description: "`{os}` to use when `platform==darwin` and `arch==arm64`" }
  os-linux-x64:
    { description: "`{os}` to use when `platform==linux` and `arch==x64`" }
  os-win32-x64:
    { description: "`{os}` to use when `platform==win32` and `arch==x64`" }
  arch-darwin: { description: "`{arch}` to use when `platform==darwin`" }
  arch-linux: { description: "`{arch}` to use when `platform==linux`" }
  arch-win32: { description: "`{arch}` to use when `platform==win32`" }
  arch-x64: { description: "`{arch}` to use when `arch==x64`" }
  arch-arm64: { description: "`{arch}` to use when `arch==arm64`" }
  arch-darwin-x64:
    { description: "`{arch}` to use when `platform==darwin` and `arch==x64`" }
  arch-darwin-arm64:
    { description: "`{arch}` to use when `platform==darwin` and `arch==arm64`" }
  arch-linux-x64:
    { description: "`{arch}` to use when `platform==linux` and `arch==x64`" }
  arch-win32-x64:
    { description: "`{arch}` to use when `platform==win32` and `arch==x64`" }
  ext-darwin: { description: "`{ext}` to use when `platform==darwin`" }
  ext-linux: { description: "`{ext}` to use when `platform==linux`" }
  ext-win32: { description: "`{ext}` to use when `platform==win32`" }
  ext-x64: { description: "`{ext}` to use when `arch==x64`" }
  ext-arm64: { description: "`{ext}` to use when `arch==arm64`" }
  ext-darwin-x64:
    { description: "`{ext}` to use when `platform==darwin` and `arch==x64`" }
  ext-darwin-arm64:
    { description: "`{ext}` to use when `platform==darwin` and `arch==arm64`" }
  ext-linux-x64:
    { description: "`{ext}` to use when `platform==linux` and `arch==x64`" }
  ext-win32-x64:
    { description: "`{ext}` to use when `platform==win33` and `arch==x64`" }

  github-token:
    description: |
      If present, and `url` is to a GitHub release asset, we will assume it's
      private and use this token to download the asset through the GitHub API.

      https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#get-a-release-asset

outputs:
  directory:
    description: Directory that was added to `$PATH` as result of setup.

  file:
    description: |
      This is always `outputs.directory/inputs.name`, which will _usually_ match
      the path to the downloaded and extracted binary. Only use this output if
      you expect that to be the case.

runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "arrow-down-circle"
  color: blue
