name: 'Setup any binary tool'
description: 'Cached download of any binary release'
inputs:
  name:
    description: "Name of the tool"
    required: true

  version:
    description: "Version of the tool"
    required: true

  url:
    description: |
      URL to installation archive. This value may contain interpolations for
      name, version, os, arch, and extension.

      http://example.com/binaries/{name}/{version}.{os}_{arch}.{ext}

      {name} and {version} will match the other inputs. {os}, {arch} and {ext},
      will be inferred, but can be changed by setting the archive-extension-
      input.

  subdir:
    description: |
      Subdirectory within the archive to find the executable(s). Supports the
      same interpolations as url.


  # Override url

  url-darwin: { description: "Override url when platform==darwin" }
  url-linux:  { description: "Override url when platform==linux" }
  url-win32:  { description: "Override url when platform==win32" }

  url-darwin-x64: { description: "Override url when platform==darwin and arch==x64" }
  url-linux-x64:  { description: "Override url when platform==linux and arch==x64" }
  url-win33-x64:  { description: "Override url when platform==win33 and arch==x64" }

  # Override subdir

  subdir-darwin: { description: "Override subdir when platform==darwin" }
  subdir-linux:  { description: "Override subdir when platform==linux" }
  subdir-win32:  { description: "Override subdir when platform==win32" }

  subdir-darwin-x64: { description: "Override subdir when platform==darwin and arch==x64" }
  subdir-linux-x64:  { description: "Override subdir when platform==linux and arch==x64" }
  subdir-win33-x64:  { description: "Override subdir when platform==win33 and arch==x64" }

  # Override {os} interpolation

  os-darwin: { description: "{os} to use when platform==darwin" }
  os-linux:  { description: "{os} to use when platform==linux" }
  os-win32:  { description: "{os} to use when platform==win32" }

  # Override {arch} interpolation

  arch-x64: { description: "{arch} to use when arch==x64" }

  arch-darwin-x64: { description: "{arch} to use when platform==darwin and arch==x64" }
  arch-linux-x64:  { description: "{arch} to use when platform==linux and arch==x64" }
  arch-win32-x64:  { description: "{arch} to use when platform==win32 and arch==x64" }

  # Override {ext} interpolation

  ext-darwin: { description: "{ext} to use when platform==darwin" }
  ext-linux:  { description: "{ext} to use when platform==linux" }
  ext-win32:  { description: "{ext} to use when platform==win32" }

  ext-darwin-x64: { description: "{ext} to use when platform==darwin and arch==x64" }
  ext-linux-x64:  { description: "{ext} to use when platform==linux and arch==x64" }
  ext-win33-x64:  { description: "{ext} to use when platform==win33 and arch==x64" }

outputs: {}

runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-down-circle'
  color: blue
