name: Check Action Typing

on:
  pull_request:

jobs:
  check_action_typing:
    name: Check Action Typing
    runs-on: docker
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
      - uses: https://github.com/typesafegithub/github-actions-typing@v2
