name: Check Action Typing

on:
  pull_request:

jobs:
  check_action_typing:
    name: Check Action Typing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check Action Typing
        uses: typesafegithub/github-actions-typing@v2
