name: Release

on:
  release:
    types:
      - released

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
